// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Server.Context;

#nullable disable

namespace Project.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260414031730_AddSecurityEnhancementsWithLoginAuditAndPasswordHistory")]
    partial class AddSecurityEnhancementsWithLoginAuditAndPasswordHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Server.Entities.Models.LoginAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LoginSuccessful")
                        .HasColumnType("bit");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAudits");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Modulo de Pagos",
                            Image = "mail-open",
                            Name = "Pagos",
                            Order = 0,
                            Path = "Payments",
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Modulo de Cobros Automaticos",
                            Image = "apps",
                            Name = "Cobros Automaticos",
                            Order = 0,
                            Path = "AutomaticPayments",
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Modulo de Cursos",
                            Image = "cash",
                            Name = "Cursos",
                            Order = 0,
                            Path = "Courses",
                            State = 1
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Modulo Estado de Cuenta",
                            Image = "cash",
                            Name = "Estado de Cuenta",
                            Order = 0,
                            Path = "AccountStatement",
                            State = 1
                        });
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Operation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Consultar Pagos",
                            Guid = "6451551a-b05c-455b-b1b9-97616e1c8892",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 1L,
                            Name = "Listar Pagos",
                            OperationKey = "",
                            Path = "Payments",
                            Policy = "Payments.List",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Creacion de pagos",
                            Guid = "2e26b4ca-bd5d-4c4f-a027-ba09f5bd448f",
                            HttpMethod = "",
                            Icon = "cash",
                            IsVisible = false,
                            ModuleId = 1L,
                            Name = "Crear Pago",
                            OperationKey = "",
                            Path = "Payments/Create",
                            Policy = "Payments.Create",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Listar Cobros Automaticos",
                            Guid = "3fd82baf-a73d-4809-8508-60dbec6119b0",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 2L,
                            Name = "Listar Cobros Automaticos",
                            OperationKey = "",
                            Path = "AutomaticPayments",
                            Policy = "AutomaticPayments.List",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 4L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Crear Cobros Automaticos",
                            Guid = "3f3f1b3b-6b0d-4eb4-8eee-cee97771f293",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 2L,
                            Name = "Crear Cobros Automaticos",
                            OperationKey = "",
                            Path = "AutomaticPayments",
                            Policy = "AutomaticPayments.Create",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 5L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Listar Cursos",
                            Guid = "def16355-a62d-4e96-8549-66d6cf66352b",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 3L,
                            Name = "Listar Cursos",
                            OperationKey = "",
                            Path = "Courses",
                            Policy = "Courses.List",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 6L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Crear Cursos",
                            Guid = "0487750b-e5d1-434a-892c-98c8df359ce1",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 3L,
                            Name = "Crear Cursos",
                            OperationKey = "",
                            Path = "Courses/Create",
                            Policy = "Courses.Create",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 7L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Actualizar Cursos",
                            Guid = "89775173-5789-4fbd-984a-14215b4ec5d4",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = false,
                            ModuleId = 3L,
                            Name = "Actualizar Cursos",
                            OperationKey = "",
                            Path = "Courses/Update",
                            Policy = "Courses.Update",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 8L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Eliminar Cursos",
                            Guid = "578a0423-c554-4cac-b5db-ef66f3dec7be",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = false,
                            ModuleId = 3L,
                            Name = "Eliminar Cursos",
                            OperationKey = "",
                            Path = "Courses/Delete",
                            Policy = "AutomaticPayments.Delete",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 9L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Estado de Cuenta Estudiante",
                            Guid = "aecb492c-69ad-480d-9646-d589b0baf93a",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 4L,
                            Name = "Estado de Cuenta Estudiante",
                            OperationKey = "",
                            Path = "AccountStatement/Student",
                            Policy = "AccountStatement.Student",
                            RouteTemplate = "",
                            State = 1
                        },
                        new
                        {
                            Id = 10L,
                            ActionName = "",
                            ControllerName = "",
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Estado de Cuenta Global",
                            Guid = "07e595dd-7330-4948-b4ab-853144ca8cbb",
                            HttpMethod = "",
                            Icon = "list",
                            IsVisible = true,
                            ModuleId = 4L,
                            Name = "Estado de Cuenta Global",
                            OperationKey = "",
                            Path = "AccountStatement/Admin",
                            Policy = "AccountStatement.Admin",
                            RouteTemplate = "",
                            State = 1
                        });
                });

            modelBuilder.Entity("Project.Server.Entities.Models.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ChangedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("ForceChange")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Description = "Super Administrator",
                            Name = "SA",
                            State = 1
                        });
                });

            modelBuilder.Entity("Project.Server.Entities.Models.RolOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("RolId");

                    b.ToTable("RolOperations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 1L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 2L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 3L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 4L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 5L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 6L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 7L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 8L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 9L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 10L,
                            RolId = 1L,
                            State = 1
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 2L,
                            RolId = 2L,
                            State = 1
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 5L,
                            RolId = 2L,
                            State = 1
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            OperationId = 9L,
                            RolId = 2L,
                            State = 1
                        });
                });

            modelBuilder.Entity("Project.Server.Entities.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationDocument")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecoveryToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Reset")
                        .HasColumnType("bit");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1L,
                            Email = "pruebas.test29111999@gmail.com",
                            FailedLoginAttempts = 0,
                            IdentificationDocument = "2987967910101",
                            MustChangePassword = false,
                            Name = "Super Administrador",
                            Number = "51995142",
                            Password = "$2a$12$86Ty8oUVWKPbU8JqCII9VO.FgM1C10dweQ4xKhM4jj1LWL9jwNu7.",
                            RecoveryToken = "",
                            Reset = false,
                            RolId = 1L,
                            State = 1,
                            UserName = "SADMIN"
                        });
                });

            modelBuilder.Entity("Project.Server.Entities.Models.LoginAudit", b =>
                {
                    b.HasOne("Project.Server.Entities.Models.User", "User")
                        .WithMany("LoginAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Operation", b =>
                {
                    b.HasOne("Project.Server.Entities.Models.Module", "Module")
                        .WithMany("Operations")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.PasswordHistory", b =>
                {
                    b.HasOne("Project.Server.Entities.Models.User", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.RolOperation", b =>
                {
                    b.HasOne("Project.Server.Entities.Models.Operation", "Operation")
                        .WithMany("RolOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Server.Entities.Models.Rol", "Rol")
                        .WithMany("RolOperations")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.User", b =>
                {
                    b.HasOne("Project.Server.Entities.Models.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Module", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Operation", b =>
                {
                    b.Navigation("RolOperations");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.Rol", b =>
                {
                    b.Navigation("RolOperations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project.Server.Entities.Models.User", b =>
                {
                    b.Navigation("LoginAudits");

                    b.Navigation("PasswordHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
